[[ray_julia]]
arch = "x86_64"
git-tree-sha1 = "88eb04f4e4a87d0a369288ceb6fb605f4ca4ff03"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[ray_julia.download]]
    sha256 = "03bc890efc63375f901325d8f67a2f3403c7d1067658ed693390276ab37f6958"
    url = "https://github.com/beacon-biosignals/Ray.jl/releases/download/v0.0.1/ray_julia.v0.0.1.x86_64-linux-gnu-julia_version+1.8.0.tar.gz"
[[ray_julia]]
arch = "aarch64"
git-tree-sha1 = "a24e4bb69ffa0baf615e27f3ae6d00084556881a"
julia_version = "1.8.0"
os = "macos"

    [[ray_julia.download]]
    sha256 = "2d5ee4e6290e1207250a02e434d588af3321d7f978fe7d57e13d4827ca7aa51b"
    url = "https://github.com/beacon-biosignals/Ray.jl/releases/download/v0.0.1/ray_julia.v0.0.1.aarch64-apple-darwin-julia_version+1.8.0.tar.gz"
[[ray_julia]]
arch = "x86_64"
git-tree-sha1 = "32c3aaecc5a1e2aed7e9ce6d9a95bef741d1ef9d"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[ray_julia.download]]
    sha256 = "1f96eaf5f35796f60b04172728caa29fc442ffcc30e8ffabfe147791dd711fc8"
    url = "https://github.com/beacon-biosignals/Ray.jl/releases/download/v0.0.1/ray_julia.v0.0.1.x86_64-linux-gnu-julia_version+1.9.0.tar.gz"
[[ray_julia]]
arch = "aarch64"
git-tree-sha1 = "81cc7a633a617a01f1fc87674258d880baa4cafb"
julia_version = "1.9.0"
os = "macos"

    [[ray_julia.download]]
    sha256 = "5969006375abafacf2fff0a1d499b492d1a883d1529e2a20fe69d3a4908f2729"
    url = "https://github.com/beacon-biosignals/Ray.jl/releases/download/v0.0.1/ray_julia.v0.0.1.aarch64-apple-darwin-julia_version+1.9.0.tar.gz"
