name = "Ray"
uuid = "3f779ece-f0b6-4c4f-a81a-0cb2add9eb95"
authors = ["Beacon Biosignals, Inc"]
version = "0.0.1"

[compat]
Aqua = "0.5"
julia = "1.8"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
