[[ray_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "644b070427bbadf1a7b3f261144536dc91e12aca"
libgfortran_version = "5.0.0"
os = "macos"

    [[ray_julia.download]]
    sha256 = "a4799c34b92761e2e2b90f81b50af86cdf9426876bcc56464c6afce677bb0209"
    url = "https://github.com/beacon-biosignals/Ray.jl/releases/download/v0.1.0/ray_julia.v0.1.0.aarch64-apple-darwin-libgfortran5-cxx11-julia_version%2B1.9.2.tar.gz"
