[[ray_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "02235c79819936e51516b2bc494b81ad99405d22"
julia_version = "1.8.0"
libgfortran_version = "5.0.0"
os = "macos"

    [[ray_julia.download]]
    sha256 = "0b9957c7edab6e2b09b374a3f2a91d7a5670a9f705b182c2e11b682e6fc67a93"
    url = "https://github.com/beacon-biosignals/Ray.jl/releases/download/v0.1.0/ray_julia.v0.1.0.aarch64-apple-darwin-libgfortran5-cxx11-julia_version+1.8.0.tar.gz"
[[ray_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "02235c79819936e51516b2bc494b81ad99405d22"
julia_version = "1.9.0"
libgfortran_version = "5.0.0"
os = "macos"

    [[ray_julia.download]]
    sha256 = "0b9957c7edab6e2b09b374a3f2a91d7a5670a9f705b182c2e11b682e6fc67a93"
    url = "https://github.com/beacon-biosignals/Ray.jl/releases/download/v0.1.0/ray_julia.v0.1.0.aarch64-apple-darwin-libgfortran5-cxx11-julia_version+1.9.0.tar.gz"
[[ray_julia]]
arch = "x86_64"
julia_version = "1.8.0"
os = "linux"

    [[ray_julia.download]]
    sha256 = "cc430cc0b3b161ae3e8463a94e60cf96605708eb1fecf89f60e0e6b30433dc9b"
    url = "https://github.com/beacon-biosignals/Ray.jl/releases/download/v0.1.0/ray_julia.v0.1.0.x86_64-linux-gnu-libgfortran5-cxx11-libstdcxx29-julia_version+1.8.0.tar.gz"
[[ray_julia]]
arch = "x86_64"
julia_version = "1.9.0"
os = "linux"

    [[ray_julia.download]]
    sha256 = "cc430cc0b3b161ae3e8463a94e60cf96605708eb1fecf89f60e0e6b30433dc9b"
    url = "https://github.com/beacon-biosignals/Ray.jl/releases/download/v0.1.0/ray_julia.v0.1.0.x86_64-linux-gnu-libgfortran5-cxx11-libstdcxx30-julia_version+1.9.0.tar.gz"
