name: Artifacts CI
on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags: ["*"]  # Triggers from tags ignore the `paths` filter: https://github.com/orgs/community/discussions/26273
    paths:
      - "Artifacts.toml"
      - ".github/workflows/artifacts_CI.yml"
  pull_request:
    paths:
      - "Artifacts.toml"
      - ".github/workflows/artifacts_CI.yml"
concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on:
      labels: ubuntu-20.04-16core
    strategy:
      fail-fast: false
      matrix:
        version:
          - "1.8"  # Version used with MVP
          - "1.9"  # Latest release
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
        - uses: actions/checkout@v3
        - uses: julia-actions/setup-julia@v1
          with:
            version: ${{ matrix.version }}
            arch: ${{ matrix.arch }}
        - uses: julia-actions/cache@v1
        - name: Install Ray CLI
          run: |
            pip install --upgrade pip wheel
            PYTHON=$(python3 --version | perl -ne '/(\d+)\.(\d+)/; print "cp$1$2-cp$1$2"')
            pip install -U "ray[default] @ https://github.com/beacon-biosignals/ray/releases/latest/download/ray-2.5.1-${PYTHON}-manylinux2014_x86_64.whl" "pydantic<2"
        - name: Delete Overrides.toml
          shell: julia --color=yes --project {0}
          run: |
            overrides_toml = joinpath(first(Base.DEPOT_PATH), "artifacts", "Overrides.toml")
            isfile(overrides_toml) && rm(overrides_toml)
        - uses: julia-actions/julia-buildpkg@v1
        - uses: julia-actions/julia-runtest@v1
          with:
            annotate: true
